### ISSUE TITLE
Lectura de extractos

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#1]

**Comment by anacid** [comment]
Solo me permite leer extractos en una única cuenta bancaria

![ScreenClip.png](https://zube.io/files/anacid/88b527ba0ab363028f1ccd3fd8aac970.png)

**Comment by gregorioruiz** [comment]
He corregido un índice y ya permite dar de alta las hojas

**Comment by anacid** [comment]
Comprobado, ya me permite leer hojas en otras cuentas bancarias
