### ISSUE TITLE
Vencimientos

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#10]
Si una factura de cliente la hemos dado por cobrado desde un movimiento de extracto de banco, debemos hacer que en vencimientos figura como que ya está remesada.

![ScreenClip.png](https://zube.io/files/anacid/f679b7ee1989932fcc53336c793fc99e.png)

**Comment by gregorioruiz** [comment]
He puesto en esta rejilla, que se vea la fecha en que se cobra por el banco

**Comment by anacid** [comment]
He dado por pagada una factura de un cliente, y en la rejilla de vencimientos no figura la fecha en que se ha cobrado por el banco.

**Comment by anacid** [comment]
En la pantalla de vencimientos no figura que la factura este cobrada, pero si vamos a "vencimientos por cliente" y localizamos el cliente, ahí si figura la fecha de cobro de la factura.
Es así como debe de figurar?
