### ISSUE TITLE
Movimientos, asignar una factura a una transferencia

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#14]
![ScreenClip.png](https://zube.io/files/anacid/9915a8f62f6f6cee9e368d40f24482f4.png)

**Comment by gregorioruiz** [comment]
No se puede poner nunca el concepto igual al que viene de la caja.
Hay que pensar cómo crear conceptos más sencillos con la información de las facturas.
Clientes:
Concepto= N. vto 16/0385 
Documento= 16/0385

En el banco: 
Concepto = Mote (o comienzo del cliente) + Documento 
Documento vacío

**Comment by gregorioruiz** [comment]
Proveedores:
Concepto:  = Concepto del gasto asociado

en el banco =
