### ISSUE TITLE
Adelantos

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#17]
Tenemos que crear "Adelantos", porque se ha dado el caso que una factura ya estaba pagada antes de grabar el gasto. 
Quizás este caso se de para clientes, tendremos que preguntarsela a Marian, aunque no creo.

**Comment by gregorioruiz** [comment]
![ScreenClip.png](https://zube.io/files/anacid/18d736a081ae248a030cb72913e897ec.png)

Poner esta forma de pago en el gasto y puntear que está pagado
