### ISSUE TITLE
Ficha de proveedor

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#19]
Añadir:
1º.- Forma de pago: se pueden usar las creadas para los clientes.
2º.- Tipo IVA
3º.- Retención
4º.- Crear un mote, para que aparezca en el "Concepto", en el alta de un gasto, y además es el que debe de figurar en concepto cuando contabilicemos. 

![ScreenClip.png](https://zube.io/files/anacid/8c1f727c8785ed51972053f1f9ce0064.png)

**Comment by anacid** [comment]
Además tenemos que modificar los CIF de los proveedores, que no figuren ni "." ni "-"

**Comment by gregorioruiz** [comment]
Hecho en el mismo proceso que la cuenta contable. Pasarlo en sus datos.

**Comment by anacid** [comment]
Visto y hecho
