### ISSUE TITLE
Visa y pagos al contado

### ISSUE THREAD

**Issue by gregorioruiz** [anacid/Gomez-Gil#23]
Copiar el dato Cuenta  de Gastos Arasti, que lo contabiliza bien.

**Comment by gregorioruiz** [comment]
Hecho en el formulario de Gastos

Queda revisar si los procesos que he puesto y que vienen de Tamesa, hacen el paso a contaplus de estos pagos o hay que copiarlo de Arasti.

**Comment by gregorioruiz** [comment]
HECHO ---------------------------

Como en el programa de la oficina, poner el sw NO LLEVAR AL 347.
Cambiado el proceso de contabilizar gastos, para tener en cuenta este nuevo dato

**Comment by anacid** [comment]
Hecho y comprobado, dado de alta gastos pagados por tarjeta y al contado, y los asientos los hace bien, contabiliza primero el pago y luego el asiento del gasto.
