### ISSUE TITLE
Hacer Gastos Directos como en Arasti

### ISSUE THREAD

**Issue by gregorioruiz** [anacid/Gomez-Gil#26]
![ScreenClip.png](https://zube.io/files/anacid/92be37af1270304a9afba267dc756539.png)

**Comment by gregorioruiz** [comment]
Hay que crear el proveedor, ponerle iva exento y creo que ya.
He hecho un asiento y va de gasto a caja.

**Comment by anacid** [comment]
Hecho y comprobado, y el asiento lo contabiliza bien
