### ISSUE TITLE
GASTOS -

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#27]
Si modificamos en un gasto dado de alta, quitar comentario --- HECHO

![ScreenClip.png](https://zube.io/files/anacid/aef9955744b3d0c01a42e6c4f67eb286.png)

**Comment by anacid** [comment]
1.- Dejar modificar la cuota del IVA, aunque la calcule.
2.- Dejar modificar la fecha de vencimiento.
3.- Al grabar un gasto, dejar ver la cuenta contable que ese proveedor tiene asociada.
![ScreenClip.png](https://zube.io/files/anacid/aa93ae23da4daca64982ce1b0eb81b57.png)

**Comment by gregorioruiz** [comment]
Copiar de Arasti. Está en la ayuda de la subcuenta de Gasto

**Comment by gregorioruiz** [comment]
Deja modificar las cuotas de iva aunque el fondo sigue siendo gris y el cursor no pasa por el dato.

Ya deja modificar también la fecha de vencimiento.
