### ISSUE TITLE
MOVIMIENTOS -

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#28]
Si seleccionamos tres movimientos y asignamos cuenta, si figura en el detalle del extracto, pero si entramos en cada movimiento solo figura la cuenta contable en el último

![ScreenClip.png](https://zube.io/files/anacid/422e8a112f72947412acdf99c7c900c4.png)

![ScreenClip.png](https://zube.io/files/anacid/6188c244ba5ca2ba3315cda673562f48.png)

**Comment by gregorioruiz** [comment]
Corregido junto con lo de que desaparecían.

**Comment by anacid** [comment]
Hecho y comprobado
