### ISSUE TITLE
Error en la estructura del fichero xdiario.

### ISSUE THREAD

**Issue by gregorioruiz** [anacid/Gomez-Gil#3]
Comparar lo que sale de aquí en bancos con lo que sale de aquí en facturas, porque eso sí se está contabilizando con su versión de contaplus. Creo que su versión está totalmente al día. Si hay que actualizar las tablas, pensar en hacerlo.

**Comment by gregorioruiz** [comment]
Tengo que instalarte la modificación y además tienes que volver a leer la hoja del banco, porque el error en el año (16 en vez de 2016) venía del proceso de lectura.

**Comment by anacid** [comment]
Esto está también hecho, ya me ha pasado los asientos
