### ISSUE TITLE
Lectura de comentarios

### ISSUE THREAD

**Issue by gregorioruiz** [anacid/Gomez-Gil#32]
Ejemplo:
SKF Española es 400 y 430

En el comentario aparece TRANSFERENCIA9999999999SKF Esp.....
y en el otro, RECIBO9999999Skf.....

Cambiar en el proceso de lectura de comentarios, que lo haga por búsqueda de trozos, todas las palabras

**Comment by anacid** [comment]
Esto esta probado y funciona
