### ISSUE TITLE
Informe de vencimientos en proveedores

### ISSUE THREAD

**Issue by gregorioruiz** [anacid/Gomez-Gil#33]
Antes lo hacía desde contaplus. Está la rejilla pero falta un informe en papel.

**Comment by anacid** [comment]
LISTADO DE VTOS. POR PROVEEDORES:

1.- No se ve la cuenta contable
2.- La cantidad de la última columna, poner "pte. pago"
3.- Intentar hacer el mismo informe que en clientes, y así unificamos de cara a Gomez.


![image](https://zube.io/files/anacid/2c96afb9dd08be6e553795fb60d527bf.png)

**Comment by anacid** [comment]
![image](https://zube.io/files/anacid/22206525c9e63e77e2942b3e6448aba6.png)
