### ISSUE TITLE
Gastos - botón verde (actualizado el 23-09)

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#34]
Comenta Marian, que al grabar gastos, y asigna compras, no pone el botón verde, habrá que repasar el proceso

**Comment by gregorioruiz** [comment]
Creo que está. 
Puedes decirle a Marian que el proceso de Aplicar compras por gastos, funciona para poner bien los verdes que hayan fallado.
![ScreenClip.png](https://zube.io/files/anacid/a4aa22501c07201a4f5ba3b063da4503.png)

**Comment by anacid** [comment]
De momento este el único gasto que he visto que tiene asociadas compras, pero en cambio no pinta el cuadro en verde.
Tendremos que revisarlo.

![ScreenClip.png](https://zube.io/files/anacid/6d86b93039e2e85978e20023bd2702e8.png)
