### ISSUE TITLE
Remesas - movimientos

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#36]
1.- En el localizador de remesas, reducir la búsqueda, por ejemplo, he visto con Marian que como a partir de ahora las remesas se van a contabilizar desde los movimientos del banco, que solo aparezcan las remesas que en C? tengan no
2.- Tenemos una remesa asociada en un movimiento del banco, pero en cambio no figura en remesas
3.- En fecha inversa, que pinta?, yo creo que es mejor que aparezca la fecha del movimiento del banco, por ejemplo.
![ScreenClip.png](https://zube.io/files/anacid/043c716036ffabc928fba8a1a43bfc45.png)

**Comment by gregorioruiz** [comment]
Creo que sólo falta decidir qué remesas quitar, aunque ahora ya se trabaja mejor.
