### ISSUE TITLE
Movimientos

### ISSUE THREAD

**Issue by anacid** [anacid/Gomez-Gil#9]
HECHO
Podemos hacer que si en un movimiento de clientes, por ejemplo, no coincide el importe de la transferencia de acuerdo con el extracto del banco con la factura que hemos asignado, ¿salte una alarma?
![ScreenClip.png](https://zube.io/files/anacid/6cc83bf163e3796796e301225c83371c.png)

**Comment by anacid** [comment]
Pendiente que confirmemos el funcionamiento de un movimiento al que asignamos una cuenta de proveedor

![ScreenClip.png](https://zube.io/files/anacid/4b563ee720fd94ba5875b8e0f0327588.png)

**Comment by anacid** [comment]
Ver como podemos poner el concepto en un movimiento de acuerdo con lo de Gomez
Este es para el caso del pago a un proveedor.
En la cuenta de banco, en concepto pone lo mismo que en el concepto de la cuenta de proveedor.

![ScreenClip.png](https://zube.io/files/anacid/a7d8b16f70ba483285fefaa4ccb8f6cc.png)

**Comment by anacid** [comment]
En el caso del cobro a un cliente, en la cuenta del banco pone el nº de remesa, y en la de cliente, la que detallo en la imagen.
Ver como podemos hacerlo para facilitarles el trabajo.

![ScreenClip.png](https://zube.io/files/anacid/e9f89694c0f7e5429a80def938d487e9.png)

**Comment by gregorioruiz** [comment]
ESTO LO HE COMPROBADO Y ESTÁ CORRECTO.

![ScreenClip.png](https://zube.io/files/anacid/6b14725c4f095a94a7cbeea5de1a2ac5.png)
![ScreenClip.png](https://zube.io/files/anacid/aadfdf42b903169fe285414ecba3d97a.png)

**Comment by gregorioruiz** [comment]
Al vincular facturas a movimientos, quedan marcadas como vencimiento no pendiente
(esto sustituye a las remesas de transferencias o cheques)

![ScreenClip.png](https://zube.io/files/anacid/09ea5a940626e4219a3b3da687f45790.png)

**Comment by gregorioruiz** [comment]
Las remesas vinculadas desde el extracto, se contabilizan con toda la hoja. No se contabilizan desde Remesas
![ScreenClip.png](https://zube.io/files/anacid/b19e10394babbb0ac868aac5670ddf96.png)

**Comment by anacid** [comment]
HECHO Y COMPROBADO, MODIFICADO EL CONCEPTO

Cuando estoy asignando una factura de un cliente, si se puede modificar el concepto de "Crear factura", por el que creas conveniente.

![ScreenClip.png](https://zube.io/files/anacid/1c501f6e1111b96ae30aa4489f5bb334.png)
